
import React, { useState, useEffect, useMemo } from 'react';
import { Medication, UserID, InventoryItem, Frequency } from '../types';
import { USERS } from '../constants';
import { Settings, Plus, Pencil, Pill, Droplets, Clock, Trash2, Mail, Repeat, ArrowDownAZ, List, Package, AlertTriangle, Copy, Check, ShoppingCart, Archive, PlayCircle, Layers, PackagePlus, History } from 'lucide-react';
import { checkStockColumnsExist, saveInventoryItem, logRestock, getSupabase } from '../services/storageService';
import { ShoppingListModal } from './ShoppingListModal';
import { RefillModal } from './RefillModal';
import { InventoryHistoryModal } from './InventoryHistoryModal';
import { EditInventoryModal } from './EditInventoryModal';

interface SettingsViewProps {
  medications: Medication[];
  inventory?: InventoryItem[];
  currentUserId: UserID;
  onEdit: (med: Medication) => void;
  onAdd: (userId: UserID) => void;
}

const REQUIRED_SQL = `
-- 1. Create Tables (Safe)
create table if not exists inventory (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  quantity numeric default 0,
  threshold numeric default 5,
  pack_size numeric default 30,
  unit text default 'pz',
  created_at timestamptz default now()
);

-- Add columns if missing (Safe update)
alter table inventory add column if not exists pack_size numeric default 30;
alter table inventory add column if not exists unit text default 'pz';

create table if not exists inventory_logs (
  id bigint generated by default as identity primary key,
  inventory_id uuid references inventory(id) on delete cascade,
  amount_added numeric not null,
  packs_added numeric not null,
  created_at timestamptz default now()
);

-- 2. Enable Realtime (Safe with DO Block)
do $$
begin
  -- Inventory
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'inventory') then
    alter publication supabase_realtime add table inventory;
  end if;
  -- Logs
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'inventory_logs') then
    alter publication supabase_realtime add table inventory_logs;
  end if;
end $$;

-- 3. Security Policies (RLS)
alter table inventory enable row level security;
alter table inventory_logs enable row level security;

drop policy if exists "Accesso Totale" on inventory;
create policy "Accesso Totale" on inventory for all using (true);

drop policy if exists "Accesso Totale" on inventory_logs;
create policy "Accesso Totale" on inventory_logs for all using (true);

-- 4. Link Medications
alter table medications add column if not exists product_id uuid references inventory(id);
`;

export const SettingsView: React.FC<SettingsViewProps> = ({
  medications,
  inventory = [],
  currentUserId,
  onEdit,
  onAdd
}) => {
  const [sortAlphabetical, setSortAlphabetical] = useState(false);
  const [missingColumns, setMissingColumns] = useState(false);
  const [sqlCopied, setSqlCopied] = useState(false);
  const [showShoppingList, setShowShoppingList] = useState(false);
  
  // Modals State
  const [refillItem, setRefillItem] = useState<InventoryItem | null>(null);
  const [editInventoryItem, setEditInventoryItem] = useState<InventoryItem | null>(null);
  const [showHistory, setShowHistory] = useState(false);

  // View Mode: 'meds' (Configuration) or 'pantry' (Inventory)
  const [viewMode, setViewMode] = useState<'meds' | 'pantry'>('pantry');
  
  const userList = currentUserId === UserID.PAOLO 
    ? [USERS[UserID.PAOLO], USERS[UserID.BARBARA]] 
    : [USERS[currentUserId]];

  useEffect(() => {
    const checkDB = async () => {
      const exists = await checkStockColumnsExist();
      setMissingColumns(!exists);
    };
    checkDB();
  }, []);

  const handleCopySql = () => {
    navigator.clipboard.writeText(REQUIRED_SQL);
    setSqlCopied(true);
    setTimeout(() => setSqlCopied(false), 2000);
  };

  const handleRefillConfirm = async (packs: number, totalUnits: number, newPackSize: number) => {
    if (!refillItem) return;
    
    // 1. Update Inventory Item (Quantity + possibly PackSize)
    const newQty = (refillItem.quantity || 0) + totalUnits;
    await saveInventoryItem({
      ...refillItem,
      quantity: newQty,
      packSize: newPackSize
    });

    // 2. Add Log
    await logRestock(refillItem.id, packs, totalUnits);
  };

  const handleInventoryEditSave = async (updatedItem: InventoryItem) => {
    await saveInventoryItem(updatedItem);
    // Note: Parent component (App) subscribes to changes, so UI will update automatically
  };
  
  const handleInventoryDelete = async (itemId: string) => {
    // We need to use supabase directly here as logic is specific to deletion
    const supabase = getSupabase();
    if(supabase) {
        await supabase.from('inventory').delete().eq('id', itemId);
        // Also clear product_id from meds
        await supabase.from('medications').update({ product_id: null }).eq('product_id', itemId);
    }
  };

  const getIcon = (iconName?: string) => {
    switch(iconName) {
      case 'drop': return <Droplets className="w-4 h-4" />;
      case 'clock': return <Clock className="w-4 h-4" />;
      case 'sachet': return <Mail className="w-4 h-4" />;
      default: return <Pill className="w-4 h-4" />;
    }
  };

  // Badge Logic
  const lowStockCount = useMemo(() => {
    const lowStockMeds = medications.filter(med => 
      !med.isArchived &&
      med.stockQuantity !== undefined && 
      med.stockThreshold !== undefined && 
      med.stockQuantity <= med.stockThreshold
    );
    const uniqueKeys = new Set<string>();
    lowStockMeds.forEach(med => {
      if (med.productId) uniqueKeys.add(`prod_${med.productId}`);
      else if (med.sharedId) uniqueKeys.add(`shared_${med.sharedId}`);
      else uniqueKeys.add(med.id);
    });
    return uniqueKeys.size;
  }, [medications]);

  return (
    <div className="pb-24 pt-6">
      
      {/* Header */}
      <div className="px-6 mb-6">
        <div className="flex items-center justify-between mb-4">
           <div>
              <h1 className="text-2xl font-bold text-gray-800 dark:text-gray-100 flex items-center gap-2">
                <Settings className="w-6 h-6 text-gray-500" /> Impostazioni
              </h1>
              <p className="text-gray-500 dark:text-gray-400 text-xs mt-1">
                Gestione {currentUserId === UserID.PAOLO ? 'Totale' : 'Personale'}
              </p>
           </div>
           
           <div className="flex gap-2">
               <button
                 onClick={() => setShowShoppingList(true)}
                 className="p-3 rounded-xl border bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-700 relative transition-colors"
               >
                 <ShoppingCart className="w-5 h-5" />
                 {lowStockCount > 0 && (
                   <span className="absolute -top-1 -right-1 w-4 h-4 bg-red-500 text-white text-[10px] font-bold rounded-full flex items-center justify-center border-2 border-white dark:border-gray-800 animate-in zoom-in">
                     {lowStockCount}
                   </span>
                 )}
               </button>
           </div>
        </div>

        {/* Toggle View Mode */}
        <div className="bg-gray-100 dark:bg-gray-800 p-1 rounded-xl flex gap-1 mb-6">
           <button
             onClick={() => setViewMode('pantry')}
             className={`flex-1 py-2 rounded-lg text-sm font-bold flex items-center justify-center gap-2 transition-all ${viewMode === 'pantry' ? 'bg-white dark:bg-gray-700 text-blue-600 dark:text-blue-300 shadow-sm' : 'text-gray-500 dark:text-gray-400'}`}
           >
             <Package className="w-4 h-4" /> Dispensa
           </button>
           <button
             onClick={() => setViewMode('meds')}
             className={`flex-1 py-2 rounded-lg text-sm font-bold flex items-center justify-center gap-2 transition-all ${viewMode === 'meds' ? 'bg-white dark:bg-gray-700 text-blue-600 dark:text-blue-300 shadow-sm' : 'text-gray-500 dark:text-gray-400'}`}
           >
             <List className="w-4 h-4" /> Farmaci
           </button>
        </div>
      </div>

      {/* Database Warning Banner */}
      {missingColumns && (
          <div className="mx-6 mb-6 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-900/50 rounded-2xl p-4 animate-in slide-in-from-top-4">
            <div className="flex items-start gap-3">
              <div className="p-2 bg-red-100 dark:bg-red-900/40 rounded-lg text-red-600 dark:text-red-400">
                <AlertTriangle className="w-5 h-5" />
              </div>
              <div className="flex-1">
                <h3 className="font-bold text-red-700 dark:text-red-300 text-sm">Database da Aggiornare</h3>
                <p className="text-xs text-red-600 dark:text-red-400 mt-1 leading-relaxed">
                   Per abilitare il Magazzino e lo Storico Rifornimenti, esegui questo SQL:
                </p>
                <div className="mt-3 bg-gray-900 rounded-lg p-3 relative group">
                  <pre className="text-[10px] text-green-400 font-mono whitespace-pre-wrap overflow-x-auto max-h-32">
                    {REQUIRED_SQL}
                  </pre>
                  <button onClick={handleCopySql} className="absolute top-2 right-2 p-1.5 bg-white/10 hover:bg-white/20 rounded text-white transition-colors">
                    {sqlCopied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

      {/* --- PANTRY VIEW (New Inventory Management) --- */}
      {viewMode === 'pantry' && (
         <div className="px-6 animate-in fade-in">
            <div className="flex items-center justify-between mb-4">
               <h2 className="text-lg font-bold text-gray-800 dark:text-gray-100">Scorte Fisiche</h2>
               <button 
                  onClick={() => setShowHistory(true)}
                  className="text-xs font-bold px-3 py-1.5 rounded-lg bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-300 flex items-center gap-1"
               >
                  <History className="w-3.5 h-3.5" /> Storico
               </button>
            </div>

            {inventory.length === 0 ? (
               <div className="text-center py-10 bg-white dark:bg-gray-800 rounded-2xl border border-dashed border-gray-200 dark:border-gray-700">
                  <Package className="w-10 h-10 text-gray-300 mx-auto mb-2" />
                  <p className="text-gray-400 text-sm">Nessun prodotto in dispensa.</p>
                  <p className="text-xs text-gray-400 mt-1">Collega i farmaci a un prodotto nelle impostazioni.</p>
               </div>
            ) : (
               <div className="grid gap-3">
                  {[...inventory].sort((a,b) => a.name.localeCompare(b.name)).map(item => {
                     const percent = Math.min(100, Math.max(0, (item.quantity / (item.packSize || 30)) * 100));
                     const isLow = item.quantity <= item.threshold;

                     return (
                        <div key={item.id} className="bg-white dark:bg-gray-800 p-4 rounded-xl border border-gray-100 dark:border-gray-700 shadow-sm flex flex-col gap-3">
                           <div className="flex items-start justify-between">
                              <div>
                                 <h3 className="font-bold text-gray-800 dark:text-gray-100">{item.name}</h3>
                                 <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">
                                    Conf. standard: <span className="font-semibold">{item.packSize}</span> {item.unit || 'unità'}
                                 </p>
                              </div>
                              <div className="flex items-center gap-2">
                                <button
                                  onClick={() => setEditInventoryItem(item)}
                                  className="p-2 text-gray-400 hover:text-blue-500 hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded-lg transition-colors"
                                >
                                    <Pencil className="w-4 h-4" />
                                </button>
                                <div className={`text-xl font-bold ${isLow ? 'text-red-500' : 'text-green-600 dark:text-green-400'}`}>
                                    {item.quantity} <span className="text-xs font-normal text-gray-400">{item.unit || ''}</span>
                                </div>
                              </div>
                           </div>

                           {/* Progress Bar */}
                           <div className="w-full bg-gray-100 dark:bg-gray-700 h-2 rounded-full overflow-hidden">
                              <div 
                                 className={`h-full ${isLow ? 'bg-red-500' : 'bg-green-500'}`} 
                                 style={{ width: `${percent}%` }}
                              />
                           </div>

                           {/* Actions */}
                           <div className="flex gap-2 mt-1">
                              <button 
                                 onClick={() => setRefillItem(item)}
                                 className="flex-1 py-2 bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-300 rounded-lg text-sm font-bold flex items-center justify-center gap-2 hover:bg-green-100 dark:hover:bg-green-900/40 transition-colors"
                              >
                                 <PackagePlus className="w-4 h-4" /> Rifornisci
                              </button>
                           </div>
                        </div>
                     );
                  })}
               </div>
            )}
         </div>
      )}

      {/* --- MEDS VIEW (Classic Configuration) --- */}
      {viewMode === 'meds' && (
        <div className="space-y-8 animate-in fade-in">
          {userList.map((user) => {
            let userMeds = medications.filter(m => m.userId === user.id);
            if (sortAlphabetical) userMeds = [...userMeds].sort((a, b) => a.name.localeCompare(b.name));
            
            const activeMeds = userMeds.filter(m => !m.isArchived);
            const archivedMeds = userMeds.filter(m => m.isArchived);

            // Raggruppamento per nome
            const groupedMeds = activeMeds.reduce((acc, med) => {
              const key = med.name.trim().toLowerCase();
              if (!acc[key]) acc[key] = [];
              acc[key].push(med);
              return acc;
            }, {} as Record<string, Medication[]>);

            const groupKeys = Object.keys(groupedMeds);
            if (sortAlphabetical) groupKeys.sort();

            return (
              <div key={user.id} className="px-6">
                <div className="flex items-center justify-between mb-4">
                  <h2 className={`text-lg font-bold flex items-center gap-2 ${user.themeColor.replace('bg-', 'text-')}`}>
                    <img src={user.avatar} className="w-6 h-6 rounded-full" alt="" />
                    Piano di {user.name}
                  </h2>
                  <button 
                    onClick={() => onAdd(user.id)}
                    className="text-xs font-bold px-3 py-1.5 rounded-lg bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-300 flex items-center gap-1"
                  >
                    <Plus className="w-3.5 h-3.5" /> Aggiungi
                  </button>
                </div>

                <div className="bg-white dark:bg-gray-800 rounded-2xl border border-gray-100 dark:border-gray-700 shadow-sm overflow-hidden mb-6">
                  {groupKeys.length > 0 ? (
                     <div className="divide-y divide-gray-50 dark:divide-gray-700">
                        {groupKeys.map(key => {
                           const group = groupedMeds[key];
                           const primary = group[0];
                           
                           // Rendering semplificato per gruppi o singoli
                           if (group.length === 1) {
                              const med = primary;
                              return (
                                 <div key={med.id} onClick={() => onEdit(med)} className="p-4 flex justify-between items-center hover:bg-gray-50 dark:hover:bg-gray-700 cursor-pointer">
                                    <div className="flex items-center gap-3">
                                       <div className="p-2 bg-gray-100 dark:bg-gray-700 rounded-lg text-gray-400">
                                          {getIcon(med.icon)}
                                       </div>
                                       <div>
                                          <h3 className="font-bold text-gray-800 dark:text-gray-100 text-sm">{med.name}</h3>
                                          <p className="text-xs text-gray-400">{med.dosage} • {med.timing}</p>
                                       </div>
                                    </div>
                                    <Pencil className="w-4 h-4 text-gray-300" />
                                 </div>
                              );
                           } else {
                              return (
                                 <div key={`g-${key}`} className="bg-white dark:bg-gray-800">
                                    <div className="p-4 bg-gray-50/50 dark:bg-gray-700/30 border-b border-gray-100 dark:border-gray-700 flex items-center gap-3">
                                       <div className="p-2 bg-blue-50 dark:bg-blue-900/20 text-blue-500 rounded-lg">
                                          {getIcon(primary.icon)}
                                       </div>
                                       <h3 className="font-bold text-gray-800 dark:text-gray-100">{primary.name} ({group.length})</h3>
                                    </div>
                                    {group.map(med => (
                                       <div key={med.id} onClick={() => onEdit(med)} className="p-3 pl-14 flex justify-between items-center hover:bg-gray-50 dark:hover:bg-gray-700 cursor-pointer border-b border-gray-50 dark:border-gray-700/50 last:border-0">
                                          <div className="text-sm text-gray-600 dark:text-gray-300">{med.timing}</div>
                                          <Pencil className="w-3.5 h-3.5 text-gray-300" />
                                       </div>
                                    ))}
                                 </div>
                              );
                           }
                        })}
                     </div>
                  ) : (
                     <div className="p-6 text-center text-gray-400 text-sm">Nessun farmaco attivo.</div>
                  )}
                </div>

                {/* Archived Section */}
                {archivedMeds.length > 0 && (
                   <div className="opacity-60">
                      <h3 className="text-xs font-bold text-gray-400 uppercase mb-2">Sospesi</h3>
                      <div className="bg-gray-50 dark:bg-gray-800/50 rounded-xl border border-gray-100 dark:border-gray-700">
                         {archivedMeds.map(med => (
                            <div key={med.id} onClick={() => onEdit(med)} className="p-3 flex justify-between items-center cursor-pointer">
                               <span className="text-sm font-medium text-gray-500 line-through">{med.name}</span>
                               <PlayCircle className="w-4 h-4 text-gray-400" />
                            </div>
                         ))}
                      </div>
                   </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* Modals */}
      <ShoppingListModal 
        medications={medications}
        isOpen={showShoppingList}
        onClose={() => setShowShoppingList(false)}
      />

      {refillItem && (
        <RefillModal
          item={refillItem}
          isOpen={!!refillItem}
          onClose={() => setRefillItem(null)}
          onConfirm={handleRefillConfirm}
        />
      )}

      {editInventoryItem && (
        <EditInventoryModal
          item={editInventoryItem}
          isOpen={!!editInventoryItem}
          onClose={() => setEditInventoryItem(null)}
          onSave={handleInventoryEditSave}
          onDelete={handleInventoryDelete}
        />
      )}

      <InventoryHistoryModal 
        isOpen={showHistory}
        onClose={() => setShowHistory(false)}
      />
    </div>
  );
};
